{% set name = "raffiot" %}
{% set version = "0.0.6.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: "v{{ version }}"
  git_url: "https://github.com/chrilves/raffiot.py"

build:
  number: 0
  script: "{{ PYTHON }} setup.py install"

requirements:
  host:
    - pip
    - python
    - typing-extensions
  run:
    - python
    - typing-extensions

test:
  imports:
    - raffiot

about:
  home: "https://github.com/chrilves/raffiot.py"
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE.txt
  summary: "Robust And Fast Functional IO Toolkit"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - chrilves
